config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pingpong_tables#index"
  get "my_profile", to: "pages#profile"
  get "playgame", to: "pages#playgame"
  get "splash", to: "pages#splash"
  get "my_profile/more", to: "pages#more"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pingpong_tables, only: %i[index show create] do
    member do
      get "play"
      get "read"
      patch "cancel"
    end

    resources :favorites, only: %i[create]
    resources :reservations, only: %i[show new create]
  end

  resources :users, only: [:show] do
    get 'favorite_tables', on: :member
  end

  resources :favorites, only: %i[show destroy]

  resources :reservations do
    member do
      patch "cancel"
    end
  end

  resources :matches do
    member do
      patch "join"
    end
  end
end

app/controllers/pingpong_tables_controller.rb
require "rqrcode"

class PingpongTablesController < ApplicationController
  def index
    @pingpong_tables = PingpongTable.all

    @markers = @pingpong_tables.geocoded.map do |pingpong_table|
      {
        latitude: pingpong_table.latitude,
        longitude: pingpong_table.longitude,

        name: pingpong_table.name,
        info_window_html: render_to_string(partial: "info_window", locals: {pingpong_table: pingpong_table }),
        marker_html: render_to_string(partial: "marker", locals: {pingpong_table: pingpong_table })
      }
    end
  end

  def show
    @pingpong_table = PingpongTable.find(params[:id])
    @my_favorite = Favorite.find_by(pingpong_table: @pingpong_table)
  end

  def taken
    @pingpong_table = PingpongTable.find(params[:id])

    # the line below makes the pingpong table unavaliable & QR code is not working
    # Please leave the line below as commented
    # @pingpong_table.update(availability: false)

    redirect_to pingpong_table_reservation_path(@pingpong_table, params[:res])
  end

  def read_qr
  end

  def play
    @ping_pong_table = PingpongTable.find(params[:id])
    @reservation = Reservation.find(params[:res])
  end

  def cancel
    @ping_pong_table = PingpongTable.find(params[:id])
    @reservation = Reservation.find(params[:res])
    @pingpong_table = @pingpong_table.reservation
    @pingpong_table.update(availability: true)

    @pingpong_table.reservation.destroy

    redirect_to root_path
  end

  def create
  end
end

app/views/pingpong_tables/_form.html.erb
<div class="container">
  <%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
</div>

app/views/pingpong_tables/_info_window.html.erb
<!-- Close button-->
<div class="button--x-infowindow container d-flex justify-content-end mb-3 me-0 p-0">
  <%= link_to root_path do %>
    <%= image_tag "close.png", {height: 20} %>
  <% end %>
</div>


<!-- TTT content -->
<div class="match-title">
  <h5><%= pingpong_table.name %></h5>

  <% if pingpong_table.availability %>
    <%= image_tag "greenface.png", {height: 20} %> AVAILABLE
  <% else %>
    <%= image_tag "redface.png", {height: 20} %> OCCUPIED
  <% end %>
</div>

<!-- "See More" button -->
<div class="details-select center mt-2">
  <%= link_to "See more", pingpong_table_path(pingpong_table), class: "button--seemore center" %>
</div>

app/views/pingpong_tables/_marker.html.erb
<div class="badge">
  <% if pingpong_table.availability %>
    <%= image_tag "marker_ava.png", height: 30, width: 30, alt: "available" %>
  <% else %>
    <%= image_tag "marker_unava.png", height: 30, width: 30, alt: "unavailable" %>
  <% end %>
</div>

app/views/pingpong_tables/index.html.erb
<style>
  .container { padding: 0; }
</style>

<div style="width: 100%; height: 87vh; position: relative"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pingpong_tables/play.html.erb
<div class="card-playtime">
  <!-- Title -->
  <div class="container pt-4 pb-2">
    <h5>Enjoy the game!</h5>
  </div>

  <!-- countdown timer -->
  <div class="centered-text m-2 timer" data-controller="gametime" data-gametime-target="timer">60:00</div>

  <!-- countdown bar -->
  <div class="container">
    <div class="timerbar">
      <div id="bar" class="bar" data-controller="timerbar" data-timer-target="timerbar"></div>
    </div>
  </div>

  <!-- Animation -->
  <div class="container center">
    <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
    <dotlottie-player src="https://lottie.host/1b81ab93-8058-4e9e-8fbf-004a4fae7d26/LN6sTCqN6H.json" background="transparent" speed="1" style="width: 340px; height: 200px;" loop autoplay></dotlottie-player>
  </div>

  <!-- Stop Playing button -->
  <div class="container">
    <button class="button--stopplaying center ms-auto me-auto" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Stop playing
    </button>
  </div>

  <!--Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header", style="background-color:#FF00F5">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmation</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Back"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to stop playing?</h\p>
      </div>
      <div class="details--seemore center">
        <%= link_to "Yes, stop", cancel_reservation_path(params[:res]), class: "button--stopplaying center", data: {turbo_method: :patch} %>
      </div>
    </div>
  </div>
</div>

app/views/pingpong_tables/read.html.erb
<div class="container m-2">
  <p>Read the QR code on the table to start playing game!</p>
</div>

<div class="card-camera">
  <div data-controller="qrreader">
    <video class="card-video" data-qrreader-target="reader"></video>
    <div data-qrreader-target="result" class="card-camera"></div>
  </div>
</div>

app/views/pingpong_tables/show.html.erb
<div class="center-card">
  <div class="card container ">
    <div class="details1 mt-3">
      <div class="details1_1 mb-2">
        <div class="button--category center">
          <%= @pingpong_table.category %>
        </div>

        <div class="availability mx-2">
          <% if @pingpong_table.availability %>
            <%= image_tag "greenface.png", {height: 20} %> AVAILABLE
          <% else %>
            <%= image_tag "redface.png", {height: 20} %> OCCUPIED
          <% end %>
        </div>
      </div>


      <div>
        <%# <%= link_to "", root_path, class: "fa-solid fa-circle-xmark fa-xl", style: "color: #ff00f5;float:right;" %>
        <%= link_to root_path do %>
          <%= image_tag "close.png", {height: 20} %>
        <% end %>
      </div>
    </div>


    <div class="photo-table center">
      <%= cl_image_tag @pingpong_table.photo.key, height: 150, width: 300, crop: :fill %>
    </div>

    <div class="name--table mt-3">
      <h5> <%= @pingpong_table.name %> </h5>
    </div>

    <div class="address--table">
      <p class="info-text"><%= image_tag "location.png", {height: 20} %> <%= @pingpong_table.address %></p>
    </div>

    <div class="description">
      <p class="info-text"><%= image_tag "note.png", {height: 20} %> <%= @pingpong_table.description %> </p>
    </div>

    <div class="details--last d-flex justify-content-between">
    <%# <% if @pingpong_table.liked_by current_user %>
    <% if  @my_favorite.nil? %>
      <%= link_to pingpong_table_favorites_path(@pingpong_table), data: {turbo_method: :post}  do %>
        <%# <i class="fa-regular fa-heart fa-2x" style="color:red"></i> %>
        <%= image_tag "heart_pixel_white.png", {height: 25} %>
      <% end %>

    <% else %>
      <%= link_to favorite_path(@my_favorite), data: {turbo_method: :delete}  do %>
        <%# <i class="fa-solid fa-heart fa-2x" style="color:red"></i> %>
        <%= image_tag "heart_pixel.png", {height: 25} %>
      <% end %>
    <% end %>

    <% if @pingpong_table.availability %>
      <button class="button--select" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Select
      </button>
    <% else %>
      <%= "" %>
    <% end %>
    </div>
  </div>


  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmation</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-center">
          <p>Do you want to reserve the table now?</p>
        </div>
        <div class="details--select center mb-3">

          <%=link_to "Reserve", pingpong_table_reservations_path(@pingpong_table), data: { turbo_method: "post"}, class: "button--seemore center" %>

        </div>
      </div>
    </div>
  </div>
</div>