config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pingpong_tables#index"
  get "my_profile", to: "pages#profile"
  get "playgame", to: "pages#playgame"
  get "splash", to: "pages#splash"
  get "my_profile/more", to: "pages#more"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pingpong_tables, only: %i[index show create] do
    member do
      get "play"
      get "read"
      patch "cancel"
    end

    resources :favorites, only: %i[create]
    resources :reservations, only: %i[show new create]
  end

  resources :users, only: [:show] do
    get 'favorite_tables', on: :member
  end

  resources :favorites, only: %i[show destroy]

  resources :reservations do
    member do
      patch "cancel"
    end
  end

  resources :matches do
    member do
      patch "join"
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footbar.html.erb
<style>
  body { Font-size: 12px !important; }
</style>

<div class="menu sticky-bottom fixed-bottom center">
  <div class="menu-details mt-3">

     <!-- Home button -->
     <div class="container menutext">
      <% if current_page?(pingpong_tables_path) %>
        <%= link_to "", pingpong_tables_path, class: "fa-solid fa-house fa-xl", style: "color: #396BEE" %>
      <% else %>
        <%= link_to "", pingpong_tables_path, class: "fa-solid fa-house fa-xl" %>
      <% end %>

      <% if current_page?(pingpong_tables_path) %>
        <p class="menutext-current mt-1">Home</p>
      <% else %>
        <p class="mt-1">Home</p>
      <% end %>
    </div>

    <!-- Reservation button -->
    <div class="container menutext">
      <% if current_page?(reservations_path) %>
        <%= link_to "", reservations_path, class: "fa-regular fa-calendar-check fa-xl", style: "color: #396BEE" %>
      <% else %>
        <%= link_to "", reservations_path, class: "fa-regular fa-calendar-check fa-xl" %>
      <% end %>

      <% if current_page?(reservations_path) %>
        <p class="menutext-current mt-1">Reservation</p>
      <% else %>
        <p class="mt-1">Reservation</p>
      <% end %>
    </div>

    <!-- Match button -->
    <div class="container menutext">
      <% if current_page?(matches_path) %>
        <%= link_to "", matches_path, class: "fa-solid fa-table-tennis-paddle-ball fa-xl", style: "color: #396BEE" %>
      <% else %>
        <%= link_to "", matches_path, class: "fa-solid fa-table-tennis-paddle-ball fa-xl" %>
      <% end %>

      <% if current_page?(matches_path) %>
        <p class="menutext-current mt-1">Match</p>
      <% else %>
        <p class="mt-1">Match</p>
      <% end %>
    </div>

    <!-- Profile button -->
    <div class="container menutext">
      <% if current_page?(my_profile_path) %>
        <%= link_to "", my_profile_path, class: "fa-solid fa-user fa-xl", style: "color: #396BEE" %>
      <% else %>
        <%= link_to "", my_profile_path, class: "fa-solid fa-user fa-xl" %>
      <% end %>

      <% if current_page?(my_profile_path) %>
        <p class="menutext-current mt-1">Profile</p>
      <% else %>
        <p class="mt-1">Profile</p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid ms-2">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "profile.png", class: "avatar", alt: "dropdown menu" %>
      <% if user_signed_in? %>
        <%= "Hi, #{current_user.nickname}!" %>
      <% else %>
        <%= "Let's Ping it" %>
      <% end %>
    <% end %>
  </div>
</div>