config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pingpong_tables#index"
  get "my_profile", to: "pages#profile"
  get "playgame", to: "pages#playgame"
  get "splash", to: "pages#splash"
  get "my_profile/more", to: "pages#more"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pingpong_tables, only: %i[index show create] do
    member do
      get "play"
      get "read"
      patch "cancel"
    end

    resources :favorites, only: %i[create]
    resources :reservations, only: %i[show new create]
  end

  resources :users, only: [:show] do
    get 'favorite_tables', on: :member
  end

  resources :favorites, only: %i[show destroy]

  resources :reservations do
    member do
      patch "cancel"
    end
  end

  resources :matches do
    member do
      patch "join"
    end
  end
end

app/views/pages/favorites.html.erb
<h2>My Favorite Tables</h2>
<ul>
  <% @favorite_tables.each do |table| %>
    <li><%= table.name %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<div style="width: 100%; height: 400px; position: relative"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pages/more.html.erb
<div data-controller="match container">
  <div class="container d-flex justify-content-between mt-3">
    <h5 class="more-title">My organized matches</h5>
  </div>

  <% if @my_matches.empty? %>
    <div class="container">
      <h5 class="gray--text">No matches yet</h5>
    </div>
  <% else %>

    <section class="slider-wrapper">
      <ul class="slides-container" id="slides-container">
        <%# <% each_slice(2) do |match_pair| %>
          <li class="slide flex-row justify-content-space-around">
            <% @my_matches.each do |match| %>
              <div class="matches-more-organised">
                <div class="m-1">
                  <div class="user--photo center m-2">
                    <%= image_tag "profile.png" , style: 'height:50px;width:50px;border-radius:50%;margin:5px;'%>
                    <!-- <p><%= current_user.nickname %></p> -->
                  </div>

                  <div class="more-matches-content center">
                    <h5 class="more-matchname mb-2"><%= match.name %></h5>
                    <p class="mb-2"><%= image_tag "calendar.png", {height: 20} %> <%= match.match_time.strftime("%b %d %Y, %I:%M %P")%></p>
                    <p class="mb-2"><%= image_tag "location.png", {height: 20} %> <%= match.location %></p>
                  </div>

                </div>
              </div>
            <% end %>
          </li>
        <%# <% end %>
      </ul>
    </section>

  <% end %>

  <div class="container d-flex justify-content-between mt-1">
    <h1 class="more-title">Joined Matches</h1>
  </div>

  <% if @my_games.empty? %>
    <div class="container">
      <h5 class="gray--text">No joined games yet</h5>
    </div>
  <% else %>
    <section class="slider-wrapper">
      <ul class="slides-container" id="slides-container">
        <%# <% @my_matches.each_slice(2) do |match_pair| %>
          <li class="slide d-flex flex-row justify-content-space-around">
            <% @my_games.each do |match| %>
              <div class="matches-more-joined">
                <div class="m-1">
                  <div class="user--photo center m-3">
                    <% if match.photo.attached? %>
                      <%= cl_image_tag match.photo.key, style: 'height:70px;width:70px;border-radius:50%;'%>
                    <% else %>
                      <%= image_tag "profile.png", style: 'height:70px;width:70px;border-radius:50%;' %>
                    <% end %>
                  </div>

                  <div class="more-matches-content center">
                    <h5 class="more-matchname mb-2"><%= match.name %></h5>
                    <p class="mb-2"><%= image_tag "calendar.png", {height: 20} %> <%= match.match_time.strftime("%b %d %Y, %I:%M %P")%></p>
                    <p class="mb-2"><%= image_tag "location.png", {height: 20} %> <%= match.location %></p>
                  </div>
                </div>
              </div>
            <% end %>
            </li>
          <%# <% end %>
      </ul>
    </section>
  <% end %>
</div>

app/views/pages/playgame.html.erb
<div class="card-playtime">
  <!-- Title -->
  <div class="container pt-4 pb-2">
    <h5>Enjoy the game!</h5>
  </div>

  <!-- countdown timer -->
  <div class="centered-text m-2 timer" data-controller="gametime" data-gametime-target="timer">60:00</div>

  <!-- countdown bar -->
  <div class="container">
    <div class="timerbar">
      <div id="bar" class="bar" data-controller="timerbar" data-timer-target="timerbar"></div>
    </div>
  </div>

  <!-- Animation -->
  <div class="container center">
    <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
    <dotlottie-player src="https://lottie.host/1b81ab93-8058-4e9e-8fbf-004a4fae7d26/LN6sTCqN6H.json" background="transparent" speed="1" style="width: 340px; height: 200px;" loop autoplay></dotlottie-player>
  </div>

  <!-- Stop Playing button -->
  <div class="container">
    <button class="button--stopplaying center ms-auto me-auto" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Stop playing
    </button>
  </div>

  <!--Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header", style="background-color:#FF00F5">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmation</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Back"></button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to stop playing?</h\p>
      </div>
      <div class="details--seemore center">
        <%= link_to "Yes, stop", root_path, class: "button--stopplaying center" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<style>
  p { Font-size: 12px !important; }
  /* h5 { Font-size: 17px !important; } */
</style>

  <!-- My Profile: My Matches -->
<div class="container d-flex justify-content-between mb-2 mt-3">
  <h5 class="mt-1">My Matches</h5>
  <h5 class="m-3 mt-0"><%= link_to "MORE", my_profile_more_path, class: "text-more me-1" %></h5>
</div>

<div data-controller="match">
  <div class="container">
    <% if @my_most_recent_match.nil? %>
      <h5 class="text-nothingyet center">No matches yet</h5>
    <% else %>
      <div class="matches-organised d-flex justify-content-evenly m-2">
        <div class="match-card mt-2 flex-shrink-0">
          <div class ="ms-4 mt-4">
            <%= image_tag "profile.png" , style: 'height:70px;width:70px;border-radius:50%;'%>
          </div>
        </div>

        <div class="flex-grow-1">
            <div class="match-title center mt-4 me-2">
              <h5><%= @my_most_recent_match.name %></h5>
            </div>

            <div class="match-matchtime center mt-2 me-2">
              <p><%= image_tag "calendar.png", {height: 20} %> <%= @my_most_recent_match.match_time.strftime("%b %d %Y, %H:%M %P") %></p>
            </div>

        </div>
      </div>
    <% end %>
  </div>
  <div class="container">
    <% if @my_most_recent_game.nil? %>
      <h5 class="text-nothingyet center">No joined matches yet</h5>
    <% else %>
      <div class="matches-joined d-flex justify-content-evenly m-2">
        <div class="match-card mt-2 flex-shrink-0">
          <div class ="ms-4 mt-4">
            <%= cl_image_tag @my_most_recent_game.photo.key, style: 'height:70px;width:70px;border-radius:50%;'%>
          </div>
        </div>


        <div class="flex-grow-1">
            <div class="match-joined-title center mt-4 me-2">
              <h5><%= @my_most_recent_game.name %></h5>

            </div>
            <div class="match-joined-matchtime center mt-2 me-2">
              <p><%= image_tag "calendar.png", {height: 20} %> <%= @my_most_recent_game.match_time.strftime("%b %d %Y, %H:%M %P") %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>


<!-- My Profile: My Favorite Tables -->
<div class="container" data-controller="favorites">
  <div class="d-flex justify-content-between">
    <% if !@my_favorite_tables.any? %>

      <div class="container p-0">
        <div class="container p-0 d-flex justify-content-space-evenly">
          <h5 class="mt-5">My Favorite Tables</h5>
        </div>

        <div class="container center mt-3">
          <h5 class="text-nothingyet2">No favorite tables yet</h5>
        </div>
      </div>

    <% elsif @my_favorite_tables.length <= 3 %>
      <div class="container p-0">
        <div class="container p-0 d-flex justify-content-space-between">
          <h5 class="mt-5">My Favorite Tables</h5>
        </div>

        <div class="container d-flex center">
          <% @my_favorite_tables.each do |favorite| %>
            <div class="container d-flex mt-2" style="max-width: 100px;">
              <%= link_to pingpong_table_path(favorite.pingpong_table) do %>
                <%= cl_image_tag favorite.pingpong_table.photo.key, :class => 'favoritetable' %>
                <p class="favtables-name mt-1"><%= favorite.pingpong_table.name %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

    <% else %>
      <div class="container p-0">
        <div class="container p-0 d-flex justify-content-between">
          <h5 class="mt-5">My Favorite Tables</h5>
          <h5 class="text-more mt-5 me-3 justify-content-end" data-action="click->favorites#fire">MORE</h5>
        </div>

        <div>
          <div class="grid center justify-content-between">
            <% @my_favorite_tables[0..2].each do |favorite| %>
              <div class="" style="max-width: 100px;">
                <%= link_to pingpong_table_path(favorite.pingpong_table) do %>
                  <%= cl_image_tag favorite.pingpong_table.photo.key, :class => 'favoritetable' %>
                  <p class='favtables-name d-none center mt-1' data-favorites-target='firstText'><%= favorite.pingpong_table.name %></p>
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="grid mb-2 d-none center justify-content-between" data-favorites-target="togglableElement">
          <% @my_favorite_tables[3..@my_favorite_tables.length].each do |favorite| %>
            <div class="" style="max-width: 100px;">
              <%= link_to pingpong_table_path(favorite.pingpong_table) do %>
              <%= cl_image_tag favorite.pingpong_table.photo.key, :class => 'favoritetable' %>
              <p class="favtables-name mt-1"><%= favorite.pingpong_table.name %></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>


  <%# if user_signed_in? %>
    <%# <div class="navbar-nav"> %>
        <%#= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
    <%# </div> %>
  <%# else %>
    <%# <div class="navbar-nav"> %>
      <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
    <%# </div> %>
  <%# end %>
</div>

app/views/pages/splash.html.erb
<style>
  body { background-color: #396BEE !important;
      color: white !important;
       }
  .navbar {
     visibility: hidden;
      }
  .menu {
     visibility: hidden;
    }
</style>

<!-- Pingpong racket icon -->
<div class="container content">
  <div class="container center mb-3">
    <%= link_to pingpong_tables_path do %>
      <%= image_tag "marker_ava.png" , style: 'height:70px;width:70px;'%>
    <% end %>
  </div>

  <!-- Headline -->
  <div class="container center">
    <h1 style="color:white">Ping it</h1>
  </div>

  <div class="container center">
    <p style="color:white">Find Pingpong Tables Nearby</p>
  </div>

  <div class="container center">
    <%= link_to pingpong_tables_path do %>
      <p class="button--start">Start</p>
    <% end %>

  </div>
</div>