config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pingpong_tables#index"
  get "my_profile", to: "pages#profile"
  get "playgame", to: "pages#playgame"
  get "splash", to: "pages#splash"
  get "my_profile/more", to: "pages#more"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pingpong_tables, only: %i[index show create] do
    member do
      get "play"
      get "read"
      patch "cancel"
    end

    resources :favorites, only: %i[create]
    resources :reservations, only: %i[show new create]
  end

  resources :users, only: [:show] do
    get 'favorite_tables', on: :member
  end

  resources :favorites, only: %i[show destroy]

  resources :reservations do
    member do
      patch "cancel"
    end
  end

  resources :matches do
    member do
      patch "join"
    end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :organiser, class_name: 'User', foreign_key:"organiser_id", optional: true
  belongs_to :buddy, class_name: 'User', foreign_key:"buddy_id", optional: true
  belongs_to :winner, class_name: 'User', foreign_key:"winner_id", optional: true

  has_one_attached :photo
  validates :name, presence: true, length: { minimum: 6 }
  validates :location, presence: true, length: { minimum: 6 }
  validates :match_time, presence: true
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[show edit update destroy]

  def index
    @matches = Match.all
    # A user can reserve one table only - how can we limit that?
  end

  def show
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    @match.organiser = current_user
    if @match.save
      redirect_to match_path(@match)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @match.update(match_params)
      redirect_to @match
    else
      render :edit
    end
  end

  def destroy
    @match.destroy
    redirect_to matches_url, status: :see_other
  end

  def join
    @match = Match.find(params[:id])
    @match.update(buddy: current_user)
    redirect_to my_profile_path
  end

  private

  def set_match
    @match = Match.find(params[:id])
  end

  def match_params
    params.require(:match).permit(:name, :match_time, :location, :equipment)
  end
end

app/views/matches/_form.html.erb
  <%= simple_form_for(@match) do |f| %>
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :match_time%>
    <div class="details--seemore mt-2">
      <%= f.submit class: "button--select center"%>
    </div>
  <% end %>

app/views/matches/edit.html.erb
<div class="container">
<div class="d-flex center mt-2">
  <h3>Edit match</h3>
</div>

<div class="card m-4 card-pingpongtable-detail_1 container p-2">
  <div class="details--seemore mt-2">

      <div class="x--btn">
        <%= link_to matches_path do %>
          <p class="center" >X</p>
        <% end %>
      </div>

  </div>

    <%= render 'form' %>

</div>
</div>

app/views/matches/index.html.erb
<style>
  p { Font-size: 12px !important; }
  h5 { Font-size: 17px !important; }
</style>

<div class="container d-flex justify-content-between mb-2 mt-3">
  <h5 class="text-pingitmatches mt-3 ms-3">Ping it Matches</h5>
  <h5 class="mt-3"><%= link_to "ADD",  new_match_path, class: "text-more mt-3 me-3" %></h5>
</div>


<div class="container mb-5">
<% @matches.each do |match| %>
  <% if current_user == match.organiser %>
    <div class="matches-organised d-flex justify-content-evenly m-2">
      <div class="mt-2 flex-shrink-0">
        <div class ="ms-4 mt-4">
          <%= image_tag "profile.png" , style: 'height:70px;width:70px;border-radius:50%;'%>
        </div>
      </div>

      <div class="flex-grow-1 mt-3">
        <div class="match-title center mt-2 me-2">
          <h5><%= match.name %></h5>
        </div>

        <div class="match-matchtime center">
          <p><%= image_tag "calendar.png", {height: 20} %> <%= match.match_time.strftime("%b %d %Y, %I:%M %P")%></p>
        </div>

        <div class="match-matchtime center">
          <p><%= link_to "Select", match, class: "button--selectmatch"%></p>
        </div>

      </div>
    </div>

  <% else %>
    <div class="matches-joined d-flex justify-content-evenly m-2">
      <div class="mt-2 flex-shrink-0">
        <div class ="ms-4 mt-4">
        <% if match.photo.attached? %>
         <%= cl_image_tag match.photo.key, style: 'height:70px;width:70px;border-radius:50%;'%>
          <% else %>
          <%= image_tag "profile.png", style: 'height:70px;width:70px;border-radius:50%;' %>
        <% end %>

        </div>
      </div>

      <div class="flex-grow-1 mt-3">
        <div class="match-joined-title center mt-2">
          <h5><%= match.name %></h5>
        </div>

        <div class="match-matchtime center">
          <p style="color:#396BEE;" ><%= image_tag "calendar.png", {height: 20} %> <%= match.match_time.strftime("%b %d %Y, %I:%M %P")%></p>
        </div>

        <div class="match-matchtime center">
          <p><%= link_to "Select", match, class: "button--selectmatch"%></p>
        </div>
      </div>
    </div>

  <% end %>
<% end %>
</div>

app/views/matches/new.html.erb
<div class="container">
<div class="d-flex center mt-2">
  <h3>New match</h3>
</div>

<div class="card m-4 card-pingpongtable-detail container p-2">
  <div class="details--seemore mt-2">

      <div class="x--btn">
        <%= link_to matches_path do %>
          <p class="center" >X</p>
        <% end %>
      </div>

  </div>

    <%= render 'form' %>

</div>
</div>

app/views/matches/show.html.erb
<div class="container d-flex justify-content-between">
  <% if current_user == @match.organiser%>
    <h5 class="text-pingitmatches mt-3">Your match</h5>
  <% else %>
    <h5 class="text-pingitmatchess mt-3"><%= User.all.sample.nickname %>'s match </h5>
  <% end %>
</div>

<% if current_user != @match.organiser %>
  <!-- Showing other user's match card -->
<div class="center-card">
  <div class="container card-joined">
    <div class="match-joined-card-detail mt-4">
      <!-- x button -->
      <div class="d-flex justify-content-end pt-2">
        <%= link_to matches_path do %>
          <%= image_tag "close.png", {height: 20} %>
        <% end %>
      </div>
      <!-- avatar img and match title -->
      <div class="container d-flex mt-3">
        <div class="mt-3">
        <% if @match.photo.attached? %>
            <%= cl_image_tag @match.photo.key, style: 'height:70px;width:70px;border-radius:50%;' %>
            <% else %>
            <%= image_tag "profile.png", style: 'height:70px;width:70px;border-radius:50%;' %>
        <% end %>

  </div>
</div>
        <div class="container ms-2">
          <div class="mt-3">
            <h5><%= @match.name %></h5>
          </div>

          <div>
            <p class="info-text"><%= image_tag "calendar.png", {height: 20} %> <%= @match.match_time.strftime("%b %d %Y, %I:%M %P") %></p>
            <p class="info-text"><%= image_tag "location.png", {height: 20} %> <%= @match.location %></p>
          </div>
        </div>
      </div>

      <!-- join button -->
      <div class="container d-flex justify-content-end mt-1">
        <%= link_to "Join", join_match_path(@match), class: "button--seemore center", data: { turbo_method: :patch}%>
      </div>
    </div>
  </div>

<% else %>
  <!-- Showing my match card -->
  <div class="container card-organised">
    <div class="match-card-detail">
      <!-- x button -->
      <div class="container d-flex justify-content-end pt-2 p-0">
        <%= link_to matches_path do %>
          <%= image_tag "close.png", {height: 20} %>
        <% end %>
      </div>

      <!-- avatar img and match title -->
      <div class="container d-flex mt-3">
        <div class="mt-3">
          <%= image_tag "profile.png" , style: 'height:70px;width:70px;border-radius:50%;'%>
        </div>

        <div class="container ms-2">
          <div class="mt-3">
            <h5><%= @match.name %></h5>
          </div>

          <div>
            <p class="info-text"><%= image_tag "calendar.png", {height: 20} %> <%= @match.match_time.strftime("%b %d %Y, %I:%M %P") %></p>
            <p class="info-text"><%= image_tag "location.png", {height: 20} %> <%= @match.location %></p>
          </div>
        </div>
      </div>

      <!-- 2 buttons -->
      <div class="container d-flex justify-content-between">
        <button class="button--cancel center" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Delete
        </button>
        <%= link_to "Edit", edit_match_path(@match), type:"button", class: "button--edit center" %>
      </div>
    </div>
  </div>
<% end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header", style="background-color:#E7D5F2">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmation</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Back"></button>
      </div>
      <div class="modal-body text-center">
        <h3>Do you want to delete this match?</h3>
      </div>
      <div class="details--select center mb-3">
        <%= link_to "Delete", match_path(@match), type:"button", class: "button--cancel center", data: {turbo_method: :delete}  %>
      </div>
    </div>
  </div>
</div>